---
# tasks file for selinux
#################################  Config Selinux on testpr1  ##########################################
- name: Confing Selinus on testpr1
  block:
    - name: Set httpd_can_network_relay flag on and keep it persistent across reboots
      seboolean: name=httpd_can_network_relay state=yes persistent=yes

    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean: name=httpd_can_network_connect state=yes persistent=yes      

  when: inventory_hostname == "testpr1"
  tags:
    - selinux_testpr1

#################################  Config Selinux on testpr2/3  ##########################################
- name: Confing Selinus on testpr2/3
  block:
    - name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
      seboolean: name=httpd_can_network_connect_db state=yes persistent=yes

  when: inventory_hostname == "testpr2" or inventory_hostname == "testpr3"
  tags:
    - selinux_testpr2_3    